---
title: "Open Science Tools"
author: "Heath Blackmon"
date: '`r Sys.Date()`'
output: ioslides_presentation
---

## Goals
>- literate programming
>- Rmarkdown - slideshows & figures
>- latex


## Literate programming
[traditional code](https://raw.githubusercontent.com/coleoguy/markdown/master/code.bad.txt)

[literate code](https://raw.githubusercontent.com/coleoguy/markdown/master/code.good.txt)

[literate code -> html ](http://coleoguy.github.io/comparative/comparative.html)

  >- *easy for others to understand (including you later)*  
  >- *easy to incorportate new data*  
  >- *easy to deal with reviewers comments*  

## Why Rmarkdown?
  >- *increasingly wide usage*
  >- *plain text*
  >- *using knitr gives simple and effective products: [pdf](http://coleoguy.github.io/saga.pdf), html, slideshows*
  >- File -> New File -> R Markdown -> html -> OK 
  
## Parts of a Rmarkdown document
 >- header
 >- text
 >- code blocks


## Challenge 1
 >- Using the template you have opened make an R markdown file that generates an html file and saves two pdf figures when you click the Knit button.
 >- 1. read in `chickwts` data
    2. make a histogram of chick weights
    3. make a barplot of chick weights parsed by feed
    4. send both of these graphs to pdf files
    ```{}
    data()
    hist()
    boxplot()
    pdf()
    dev.off()
    ```
 
 
## Challenge 2
 >- Save a second copy of your markdown file and change it into a slideshow
 >- 1. change output argument in header
    2. use the `echo = F` argument in your code blocks
    3. delete the pdf saves

## Conclusion
 >- comment/document/organize
 >- Collaboration is one of the most fun/productive ways of doing science.

